/*
 * https://github.com/but80/fmfm.core
 */

package vavi.sound.yamaha.ma.cmd.cli.internal.player;

import java.io.IOException;
import java.io.InputStream;
import java.time.Duration;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.atomic.AtomicReference;
import java.util.function.Consumer;
import java.util.function.Supplier;
import javax.sound.sampled.AudioFormat;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;


// The Renderer renders waveforms for output to an audio device.
// TODO: rename
public class Renderer {

    public AudioFormat Parameters;
    AudioInputStream stream;
    List<Insertion> insertions;

    // NewRenderer creates a new Renderer.
    public Renderer() throws LineUnavailableException {
        insertions = new ArrayList<>();

        var h = AudioSystem.getSourceDataLine(Parameters);
        var selectedDevinfo = h.getLineInfo();
        System.err.printf("Audio device: %s\n", selectedDevinfo.toString());

        // var selectedDevinfo *portaudio.DeviceInfo
        // devinfos, err := portaudio.Devices()
        // if err != nil {
        // 	panic(err)
        // }
        // for _, devinfo := range devinfos {
        // 	if 0 < devinfo.MaxOutputChannels {
        // 		if deviceName == devinfo.name {
        // 			selectedDevinfo = devinfo
        // 		}
        // 	}
        // }
        // if selectedDevinfo == nil {
        // 	panic("device not found")
        // }

        this.Parameters = new AudioFormat(44100, 16, 2, true, false);
        // params := portaudio.StreamParameters{
        // 	Output: portaudio.StreamDeviceParameters{
        // 		Device: selectedDevinfo,
        // 		channels: selectedDevinfo.MaxOutputChannels,
        // 		Latency: selectedDevinfo.DefaultHighOutputLatency,
        // 	},
        // 	SampleRate: sampleRate,
        // 	FramesPerBuffer: 0,
        // }
    }

    // Insert adds an insertion effect.
    public void Insert(vavi.sound.yamaha.ma.cmd.cli.internal.player.Insertion insertion) {
        this.insertions.add(insertion);
    }

    // Start begins outputting the waveform generated by the processor to the audio device.
    public void Start(Supplier<double[]> processor, Consumer<Integer> controller) throws UnsupportedAudioFileException, IOException {
        var startTime = Instant.now();
        var maxLevel = new AtomicReference<>(32766.0 / 32767.0);

        System.err.printf("insertion %s\n", this.insertions);

        this.stream = AudioSystem.getAudioInputStream(new InputStream() {
            @Override public int read() throws IOException {
                byte[] b = new byte[1];
                int r = read(b, 0, 1);
                return r == -1 ? -1 : b[0] & 0xff;
            }
            @Override public int read(byte[] b, int ofs, int len) {
                // midiLatency := float64(this.stream.Info().OutputLatency) / float64(time.Millisecond)
                var sampleLen = 1000.0 / Parameters.getSampleRate();
                var midiLatency = (double) (len) * sampleLen;
                var now = Duration.between(startTime, Instant.now()).toMillis();
                for (var i = 0; i < len; i += 2) {
                    now += sampleLen;
                    controller.accept((int) (now - midiLatency));

                    var lr = processor.get();
                    for (var insertion : insertions) {
                        lr = insertion.Next(lr[0], lr[1]);
                    }

                    if (maxLevel.get() < lr[0] || maxLevel.get() < lr[1]) {
                        if (maxLevel.get() < lr[0]) {
                            maxLevel.set(lr[1]);
                        }
                        if (maxLevel.get() < lr[0]) {
                            maxLevel.set(lr[1]);
                        }
                        var db = Math.log10(maxLevel.get()) * 20.0;
                        System.err.printf("Clipping occurred: %2.1f\n", db);
                    }

                    b[i * 2 + 0] = (byte) lr[0];
                    b[i * 2 + 1] = (byte) lr[1];
                }
                return len;
            }
        });

        System.err.printf("Sample rate: %f\n", this.stream.getFormat().getSampleRate());
        System.err.printf("Output latency: %s\n", "TODO");

//        this.line.start();
    }
}
